### ISSUE TITLE
[Report] graph 프레임워크 적용

### ISSUE THREAD

**Issue by feel5ny** [huusz/Da-Da#12]
- [x] ReportSubNav 날짜 데이터 리듀서&액션 생성 (오늘 날짜 및 7일전 날짜 state로 관리)
- [x] 특정 기간 칼로리 & 영양성분 데이터 get 구현 (with date 리듀서)
- [x] 칼로리 차트에 데이터 적용
- [x] 영양소 차트에 데이터 적용

**Comment by huusz** [comment]
- [ ] ReportSubNav 날짜 데이터 리듀서&액션 생성 (오늘 날짜 및 7일전 날짜 state로 관리)
- [ ] 날짜 이동 구현
- [ ] 특정 기간 칼로리 & 영양성분 데이터 get 구현 (with date 리듀서)
- [ ] get한 데이터 차트에 적용
