### ISSUE TITLE
[Weight] GET/POST/DELETE

### ISSUE THREAD

**Issue by 22hyeseung** [huusz/Da-Da#120]
- [x] API
- [x] UI이슈

**Comment by feel5ny** [comment]
UI 이슈
- [x] 목표체중, 시작체중 연결
- [ ] input 값을 받을 때, 목표체중과 시작체중 사이의 값만 받을 수 있도록 한다.
- [x] 목표체중과 시작체중 연결후, flag 위치 계산식 적용
- [ ] 리스트 - 이전 몸무게와 비교 후 화살표 렌더링
- [x] 그래프와 getAllWeight 값 연결

**Comment by feel5ny** [comment]
API
- [x] GET
- [x] POST
- [x] DELETE

**Comment by feel5ny** [comment]
## DELETE 이슈
> 해결 : 백엔드에서 null을 제외하는 조건을 걸어서 get을 보내주면 된다고 함.

### 문제의 흐름
1. 현재 api get으로는 4개만 받을 수 있음
2. 이 상황에서 4개중 delete를 할 경우, day_log_kg이 null로 치환된다. (배열의 길이는 그대로 4를 유지한다.)
3. 렌더링에서는 null값을 제외하고 렌더링하기 때문에,  보여지는 리스트는 줄어든다. (하지만 get에서 4개만 받는 상황이기때문에, 배열은 그대로 4로 유지되어있음)
4. 즉, 로그가 4개 이상일때 자동으로 채워지지 않는다...


### 솔루션 제안
- delete에서 원하는  view: (현재 로그가 4개 이상이 있다고 생각한다면) delete를 하면, 하나가 채워지는 형식
- 제안하는 해결방법 : 전체 log를 불러온다 > front에서 4개의 배열 요소만 렌더
> 이 방법을 사용할 경우에는 post나 delete 후 get하는 방법의 디자인 패턴은 사용하면 안될 듯. 
> 대신에, 비동기처리방법을.
> ### POST
> 1. 전체 log를 부른 후 reducer에 저장
> 2. post는 응답코드를 기존 reducer 배열의 첫번째 배열에 재할당하는 방식
> ### DELETE
> 1. 전체 log를 부른 후 reducer에 저장
> 2. delete 할때, 해당 id값의 배열 요소를 삭제하는 방식

>> ### 의문.. 
>> 그냥 바로 전체 get하는 것이 좋은가 ?(좋지 않은 디자인패턴이라고 생각했던 부분)
>> 아니면 reducer에서 여러가지 조건을 처리해서 코드가 길어지는 것이 좋은가?

**Comment by feel5ny** [comment]
- [x] 그래프 연동 버그
