### ISSUE TITLE
2017-10-25 코드 리뷰

### ISSUE THREAD

**Issue by seungha-kim** [huusz/Da-Da#176]
1. 미들웨어의 재사용

https://github.com/huusz/Da-Da/blob/d0189845141c678f6b0cbbf7da42e147e6437a9f/backend/src/router/foods.js#L14

현재 `express-jwt`나 `cors` 같은 미들웨어가 여러 라우터 파일에서 생성되고 있는데, 이렇게 같은 일을 하는 코드가 중복되어 있는 것은 좋지 않습니다. `middleware.js` 등의 파일로 따로 빼서 거기에서 미들웨어를 생성하신 뒤에, 라우터 파일에서 그놈들을 require 해서 재사용하시는 것을 추천드립니다.

2. 쿼리의 재사용

https://github.com/huusz/Da-Da/blob/d0189845141c678f6b0cbbf7da42e147e6437a9f/backend/src/query.js#L233-L245

이 부분에서 `first`를 제외한 모든 부분이 아래에 중복 작성되어 있습니다.

https://github.com/huusz/Da-Da/blob/d0189845141c678f6b0cbbf7da42e147e6437a9f/backend/src/query.js#L207-L218

[보강에서 다뤘던 쿼리 재사용 방법](https://github.com/wpsn/wpsn-knex-in-depth#미리-작성해둔-쿼리를-이용해-다른-쿼리-만들기)을 여기에 적용할 수 있습니다. 쿼리 빌더를 사용하는 만큼 쿼리 빌더의 장점을 잘 활용해야 포트폴리오로써의 가치를 높일 수 있겠죠?

**Comment by KimSejune** [comment]
확인하고 해결했습니다!!
