### ISSUE TITLE
[Diary] 푸드, 피트니스 데이터 수정 오류

### ISSUE THREAD

**Issue by 22hyeseung** [huusz/Da-Da#204]
- [x] [Diary/Food] 수정 시 모달의 등록 버튼이 아예 반응하지 않음
- [x] [Diary/Fitness] 수정 시 kcal가 0으로 변함

**Comment by feel5ny** [comment]
[Diary/Fitness] 수정 시 kcal가 0으로 변함
> unitKcal가 undefined로 옴
> api 문서 put 응답코드에 unitKcal 칼럼 추가

**Comment by feel5ny** [comment]
~Food 탭 수정 > 수정적용은 되나, 타이밍 이슈 생김. > 수요일에 여쭤보기~
