### ISSUE TITLE
[bug] 최초 회원정보 등록시 넘어가지지 않는 현상

### ISSUE THREAD

**Issue by downmix** [huusz/Da-Da#258]
여러 이유들이 상충되어 발생하는 현상으로 내용이 길어져서 이슈로 등록합니다.

## 개요
로그인 이후 최초 회원정보 페이지에서 다음페이지로 진행이 안되는현상

## 현상
- GET regret이 pedding 되어 오작동될 여지가 생기는 문제
- POST /user/first 를 처리하지않고 진행되지 않는 문제
- POST /user/first 를 처리하지않았기 때문에 페이지가 계속 loop됨
- 되는사용자가 있고, 안되는 사용자가 있는문제

### 백엔드 조치
- GET regret 에서 해당조건의 데이터가 없을경우 통신이 pedding되는 상태. 
- 로그인 로딩시 전날 사용자의 기록을 가져오는데, 최초 가입시에는 전날 기록이 없다.
- 때문에 오류코드와 공백형태로 반환하여 pedding 되는 현상을 막아야 통신충돌을 막을수가 있음
- 뒤늦게 failed나 canceled 되는데, 이럴경우 원하지 않는 데이터가 프론트에서 사용되는 경우가 생김

### 프론트엔드 조치
- POST /user/first 에서 promise로 페이지 처리를 하였지만, promise가 정상처리 되지 않는것을 확인
- promise 문법에 맞게 재작성

### 환경적 조치
- 기존코드로 동작하는이유는 크롬의 유연한 동작으로 오류 없이 처리되는 현상.
- 크롬 자체적으로 개발자모드가 활성화 여부에 따라, js엔진이 다르게 동작하여 사용자별로 다른 현상이 생긴다.
- 강사님 로그인이 안된이유도 개발자모드의 크롬(또는 파이어폭스). 우리가 테스트했을때는 일반 크롬이었기 때문에 다른상황이 발생했다.

**Comment by 22hyeseung** [comment]
WoW.... 수고하셨습니다..!!!
