### ISSUE TITLE
[dummy-data]Food

### ISSUE THREAD

**Issue by suhyeon** [huusz/Da-Da#26]
- food 분담
1. 항목
- 음료, 채소.야채, 과일, 고기, 생선, 과자, 견과류, 소스.잼류, 빵, 시리얼, 유제품, 파스타.쌀.국수, 패스트푸드, 수프.국, 기타

**Comment by suhyeon** [comment]
음료, 채소.야채, 과일, 고기, 생선

**Comment by KimSejune** [comment]
과자, 견과류, 소스.잼류, 빵, 시리얼  각 4개씩 작성

**Comment by suhyeon** [comment]
옥택님 꼴찌!!

**Comment by downmix** [comment]
저도 빠르게 채우도록 하겠습니다 ㅠ
유제품, 파스타.쌀.국수, 패스트푸드, 수프.국, 기타
