### ISSUE TITLE
[front] 퍼블리싱 수정건의

### ISSUE THREAD

**Issue by downmix** [huusz/Da-Da#31]
1) 로그인 페이지의 동영상 파일사이즈 조정
기존 3.6MB에서 917KB로 압축 했지만, 풀스크린에서 해상도가 많이 뭉개지는 문제가 있어 압축률을 좀더 조정하였습니다. 1.5MB 파일이 화질을 조금 더 높인것으로 비교검토하여 적용하면 될거같습니다.

2) 검색페이지
일부 dip가 조정된 pc에서 화면이 짤리는 문제가 있는거 같습니다.
SearchPage >> container의 width값을 고정값으로 되어있는데요.
width: '1439px' 를 width: '100%' 로 변경 하는것도 좋을거 같습니다.
아니면 다른 페이지와 동일한 width를 가져가야 될거 같습니다.

3) 다이어리페이지 
이부분은 저도 확인을 덜 했는데,
diary-food-meal-list-card 부분에 가로스크롤 ui인데, 윈도우 환경에서 좌우 스크롤이 지원한가요? 
보통 좌우 스크롤버튼을 만들거나, 간단하게 x축 스크롤바를 만들어서 대응하는것으로 알고있습니다.

**Comment by feel5ny** [comment]
네 퍼블쪽은 저희가 지금 완성도 있는 상태가 아니라서, merge 이후에 계속 작업할예정입니다. 참고해주세요
1. 1.5가 나을거 같네요.
2. 수정예정
3. 스크롤 들어갈 예정입니다.

**Comment by downmix** [comment]
네, 이 이슈들은 미확정적인것도 많기때문에, 가볍게 보고 넘기면 될거같습니다.

**Comment by feel5ny** [comment]
넵 백엔드 화이팅 -!

**Comment by 22hyeseung** [comment]
2번째 검색페이지 너비 건의하신 내용 반영하였습니다 :>
늦어져서 죄송합니다.. ㅇ_ㅠ
