### ISSUE TITLE
[Food] Food 페이지 search & get/post/delete/update

### ISSUE THREAD

**Issue by feel5ny** [huusz/Da-Da#83]
- 검색시 header에 토큰값 날려야함.
- fetch(`${rooturl}`/foods?name=`${foodSource.title}`)

- [x] GET
- [x] POST
- [x] DELETE
- [x] UPDATE
- [x] 추가이슈(1차)
- [x] 추가이슈(2차)

**Comment by feel5ny** [comment]
- [x] 검색구현
- [x] get/post

**Comment by feel5ny** [comment]
추가 이슈 1차

> **검색결과**

1. 문자로 시작되는부분, 가나다순
~~2. 검색결과 후, '먹은 음식을 선택 후 양을 넣어보세요'라는 문구가 출력이 안됨~~
3. (우선순위 낮음) 검색 후에 오른쪽에 나오는 g당 칼로리에 대한 설명이 부족함. > 설명문구를 추가하거나, 다른 값을 렌더해야할 듯
4. 검색결과 후, select해서 먹은 양을 넣을 때, '?' 모양 아이콘 hover popup에 인분당 g수에 대한 일반적인 값의 정보를 넣어주자.(혹은 관련 정보 링크 넣기)

**Comment by feel5ny** [comment]
[TroubleShoot > 다이어리/food-Search] 
- 문자로 시작되는부분, 가나다순 > sort()를 map을 한번 돌리고 나서 넣어줘야하나? 

~[프론트엔드 환경 논의]~
~post 보낼때, 마지막 key값에는 콤마를 빼야하는데, 현재 prettier는 콤마를 자동생성함~
~[백엔드 논의]~
~post 응답 json의 키값과 get에서 json 키값 통일가능한지 (=바로 계산해서 응답코드로?)~
~> 그렇지 않으면.. 다시 post와 fetch를 동시에 해야함~

**Comment by feel5ny** [comment]
추가 이슈 2차
~~- [x] 두번째 post부터 tag명이 날라가지 않음~~
- [x] 전반적으로 component화!
- [x] (코드 명시성(?))food에서 전체를 get하면 food_log와 recipe_log로 받는데, 현재는 action에서 인자를 하나를 받은 후, reducer에서 쪼개주는 상태이다. > 명시성을 위해서 추후에 payload형태를 객체 내부에 2개의 인자를 받는 형태로 하며, reducer에서 업데이트 시켜주는 식으로 수정하자.

**Comment by huusz** [comment]
Food탭 Summary 부분은 제가 하겠습니다!
